import { GetServerSidePropsContext, GetServerSidePropsResult } from "next";
import Head from "next/head";
import Image from "next/image";

type Props = {
  character_list: {
    char_id: number;
    char_name: string;
    photo: string;
    icon: string;
    fans_num: number;
    vote_num: number;
    position: number;
    video_url: string;
    video_img: string;
    share_img: string;
    description: string;
    note: string;
    info: string;
    is_vote: number;
    user_vote_num: number;
  }[];
};

export default function IndexPage({ character_list }: Props) {
  return (
    <>
      <Head>
        <title>《乘风2023》嘉宾安利排名</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="section">
        <div className="columns is-mobile is-multiline">
          {character_list.map(
            (
              {
                char_id,
                char_name,
                photo,
                fans_num,
                vote_num,
                description,
                note,
              },
              index
            ) => (
              <div
                key={char_id}
                className="column is-4-mobile is-3-tablet is-2-desktop is-relative has-text-centered"
              >
                <Image src={photo} alt={char_name} width={210} height={229} />
                <div className="control">
                  <div className="tags has-addons are-normal">
                    <span className="tag is-dark">投票</span>
                    <span className="tag is-link">{vote_num}</span>
                  </div>
                </div>
                {description && <p>{description}</p>}
                {note && <p>{note}</p>}
              </div>
            )
          )}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(
  context: GetServerSidePropsContext
): Promise<GetServerSidePropsResult<Props>> {
  const response = await fetch(
    "https://vipact.api.mgtv.com/api/v1/act/vote/charlist?act_name=20230414cf2023&count=50"
  );
  if (!response.ok) {
    throw new Error(`HTTP ${response.status}`);
  }
  const data = await response.json();
  if (data.ret !== 0) {
    throw new Error(`API ${data.errno}`);
  }
  return {
    props: data.data,
  };
}
